name: Python backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
          playwright install chromium
          playwright install-deps chromium

      - name: Create instance directory
        run: |
          mkdir -p instance

      - name: Lint with ruff
        run: |
          ruff check .

      - name: Test with pytest
        run: |
          PYTHONPATH=. pytest
